version: "2.1"

services:
  jolokia:
    image: jolokia/java-jolokia
    volumes:
      - /opt/jolokia/

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'kafka:8083'
      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://kafka:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  kafka:
    image: landoop/fast-data-dev:latest
    environment:
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_SUPER_USERS: User:kafka;
      KAFKA_PRINCIPAL_BUILDER_CLASS: de.thmshmm.kafka.CustomPrincipalBuilder
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      ADV_HOST: kafka
      FORWARDLOGS: 0
      #REST_PORT: 0
      RUNTESTS: 0
      SAMPLEDATA: 1
      SUPERVISORWEB: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      #KAFKA_BROKER_ID: 101
      BROKER_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=port=19581,host=0.0.0.0"
      ZOOKEEPER_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=port=19585,host=0.0.0.0"
      SCHEMA_REGISTRY_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=port=19582,host=0.0.0.0"
      CONNECT_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=port=19584,host=0.0.0.0"
      # following are required to run SQL Processors in Connect mode (manualy uploaded connector is also required!)
      CONNECT_CONFIG_PROVIDERS: aes256
      CONNECT_CONFIG_PROVIDERS_AES256_CLASS: io.lenses.connect.secrets.providers.Aes256DecodingProvider
      CONNECT_CONFIG_PROVIDERS_AES256_PARAM_AES256_KEY: PasswordPasswordPasswordPassword
      CONNECT_CONFIG_PROVIDERS_AES256_PARAM_FILE_DIR: /tmp/connect-secrets
    ports:
      - 9001:9001 # supervisor web
      - 9092:9092 # kafka
      - 2181:2181 # zookeeper
      - 8083:8083 # connect
      - 8081:8081 # schema-registry
      - 9581:9581 # kafka jmx
      - 9585:9585 # zookeeper jmx
      - 9584:9584 # connect jmx
      - 9582:9582 # schema-registry jmx
      - 3030:3030 # ui
      - 19581:19581 # kafka jolokia
      - 19585:19585 # zookeeper jolokia
      - 19582:19582 # schema registry jolokia
      - 19584:19584 # connect jolokia
      - 3333:3333 # visualvm
    volumes:
      - ${CONNECTOR_PATH?"An absolute host path where the EMS Kafka connector jar can be found"}:/connectors/
    volumes_from:
      - jolokia
