/*
 * Copyright 2023 Celonis SE
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.celonis.kafka.connect.ems.config
import com.celonis.kafka.connect.ems.config.EmsSinkConfigConstants._
import com.typesafe.scalalogging.LazyLogging
import org.apache.kafka.common.config.ConfigDef
import org.apache.kafka.common.config.ConfigDef.Importance
import org.apache.kafka.common.config.ConfigDef.Type

object EmsSinkConfigDef {
  val config: ConfigDef = new EmsSinkConfigDef()
    .define(
      ENDPOINT_KEY,
      Type.STRING,
      Importance.HIGH,
      ENDPOINT_DOC,
      "Connection",
      1,
      ConfigDef.Width.LONG,
      "Endpoint",
    )
    .define(
      AUTHORIZATION_KEY,
      Type.PASSWORD,
      Importance.HIGH,
      AUTHORIZATION_DOC,
      "Connection",
      2,
      ConfigDef.Width.MEDIUM,
      "Authorization Key",
    )
    .define(
      TARGET_TABLE_KEY,
      Type.STRING,
      Importance.HIGH,
      TARGET_TABLE_DOC,
      "Connection",
      3,
      ConfigDef.Width.MEDIUM,
      "Table",
    )
    .define(
      CONNECTION_ID_KEY,
      Type.STRING,
      CONNECTION_ID_DEFAULT,
      Importance.HIGH,
      CONNECTION_ID_DOC,
      "Connection",
      4,
      ConfigDef.Width.MEDIUM,
      "Connection Id",
    )
    .define(
      COMMIT_SIZE_KEY,
      Type.LONG,
      Importance.HIGH,
      COMMIT_SIZE_DOC,
      "Commit",
      1,
      ConfigDef.Width.MEDIUM,
      "File Size",
    )
    .define(
      COMMIT_RECORDS_KEY,
      Type.INT,
      Importance.HIGH,
      COMMIT_RECORDS_DOC,
      "Commit",
      2,
      ConfigDef.Width.MEDIUM,
      "Max records",
    )
    .define(
      COMMIT_INTERVAL_KEY,
      Type.LONG,
      Importance.HIGH,
      COMMIT_INTERVAL_DOC,
      "Commit",
      3,
      ConfigDef.Width.MEDIUM,
      "Time window",
    )
    .define(
      TMP_DIRECTORY_KEY,
      Type.STRING,
      Importance.LOW,
      TMP_DIRECTORY_DOC,
    )
    .define(
      PRIMARY_KEYS_KEY,
      Type.STRING,
      PRIMARY_KEYS_DEFAULT,
      Importance.LOW,
      PRIMARY_KEYS_DOC,
      "Data",
      1,
      ConfigDef.Width.MEDIUM,
      "Primary Keys",
    )
    .define(
      FALLBACK_VARCHAR_LENGTH_KEY,
      Type.INT,
      FALLBACK_VARCHAR_LENGTH_DEFAULT,
      Importance.LOW,
      FALLBACK_VARCHAR_LENGTH_DOC,
      "Data",
      2,
      ConfigDef.Width.MEDIUM,
      "String(VARCHAR) type size",
    )
    .define(
      ERROR_POLICY_KEY,
      Type.STRING,
      ERROR_POLICY_DEFAULT,
      Importance.HIGH,
      ERROR_POLICY_DOC,
      "Error",
      1,
      ConfigDef.Width.LONG,
      ERROR_POLICY_DOC,
    )
    .define(
      NBR_OF_RETRIES_KEY,
      Type.INT,
      NBR_OF_RETIRES_DEFAULT,
      Importance.MEDIUM,
      NBR_OF_RETRIES_DOC,
      "Error",
      2,
      ConfigDef.Width.LONG,
      NBR_OF_RETRIES_KEY,
    )
    .define(
      ERROR_RETRY_INTERVAL,
      Type.LONG,
      ERROR_RETRY_INTERVAL_DEFAULT,
      Importance.MEDIUM,
      ERROR_RETRY_INTERVAL_DOC,
      "Error",
      3,
      ConfigDef.Width.LONG,
      ERROR_RETRY_INTERVAL,
    )
    .define(
      PARQUET_ROW_GROUP_SIZE_BYTES_KEY,
      Type.INT,
      PARQUET_ROW_GROUP_SIZE_BYTES_DEFAULT,
      Importance.MEDIUM,
      PARQUET_ROW_GROUP_SIZE_BYTES_DOC,
      "Parquet",
      1,
      ConfigDef.Width.LONG,
      PARQUET_ROW_GROUP_SIZE_BYTES_KEY,
    )
    .define(
      DEBUG_KEEP_TMP_FILES_KEY,
      Type.BOOLEAN,
      DEBUG_KEEP_TMP_FILES_DEFAULT,
      Importance.LOW,
      DEBUG_KEEP_TMP_FILES_DOC,
      "Parquet",
      2,
      ConfigDef.Width.SHORT,
      DEBUG_KEEP_TMP_FILES_KEY,
    )
    .define(
      OBFUSCATED_FIELDS_KEY,
      Type.STRING,
      null,
      Importance.LOW,
      OBFUSCATED_FIELDS_DOC,
      "Obfuscation",
      1,
      ConfigDef.Width.LONG,
      OBFUSCATED_FIELDS_DOC,
    )
    .define(
      OBFUSCATION_TYPE_KEY,
      Type.STRING,
      "FIX",
      Importance.LOW,
      OBFUSCATION_TYPE_DOC,
      "Obfuscation",
      2,
      ConfigDef.Width.SHORT,
      OBFUSCATION_TYPE_KEY,
    )
    .define(
      SHA512_SALT_KEY,
      Type.STRING,
      null,
      Importance.LOW,
      SHA512_SALT_DOC,
      "Obfuscation",
      3,
      ConfigDef.Width.MEDIUM,
      SHA512_SALT_DOC,
    )
    .define(
      SHA512_RANDOM_SALT_KEY,
      Type.BOOLEAN,
      null,
      Importance.LOW,
      SHA512_RANDOM_SALT_DOC,
      "Obfuscation",
      4,
      ConfigDef.Width.MEDIUM,
      SHA512_RANDOM_SALT_DOC,
    )
    .define(
      PROXY_HOST_KEY,
      Type.STRING,
      null,
      Importance.LOW,
      PROXY_HOST_DOC,
      "Proxy",
      1,
      ConfigDef.Width.MEDIUM,
      PROXY_HOST_DOC,
    )
    .define(
      PROXY_PORT_KEY,
      Type.INT,
      null,
      Importance.LOW,
      PROXY_PORT_DOC,
      "Proxy",
      2,
      ConfigDef.Width.MEDIUM,
      PROXY_PORT_DOC,
    )
    .define(
      PROXY_TYPE_KEY,
      Type.STRING,
      "HTTP",
      Importance.LOW,
      PROXY_TYPE_DOC,
      "Proxy",
      3,
      ConfigDef.Width.MEDIUM,
      PROXY_TYPE_DOC,
    )
    .define(
      PROXY_AUTHENTICATION_KEY,
      Type.STRING,
      null,
      Importance.LOW,
      PROXY_AUTHENTICATION_DOC,
      "Proxy",
      4,
      ConfigDef.Width.MEDIUM,
      PROXY_AUTHENTICATION_DOC,
    )
    .define(
      PROXY_AUTHBASIC_USERNAME_KEY,
      Type.STRING,
      null,
      Importance.LOW,
      PROXY_AUTHBASIC_USERNAME_DOC,
      "Proxy",
      5,
      ConfigDef.Width.MEDIUM,
      PROXY_AUTHBASIC_USERNAME_DOC,
    )
    .define(
      PROXY_AUTHBASIC_PASSWORD_KEY,
      Type.PASSWORD,
      null,
      Importance.LOW,
      PROXY_AUTHBASIC_PASSWORD_DOC,
      "Proxy",
      6,
      ConfigDef.Width.MEDIUM,
      PROXY_AUTHBASIC_PASSWORD_DOC,
    )
    .define(
      EXPLODE_MODE_KEY,
      Type.STRING,
      "None",
      Importance.LOW,
      EXPLODE_MODE_DOC,
      "Explode",
      1,
      ConfigDef.Width.MEDIUM,
      EXPLODE_MODE_DOC,
    )
    .define(
      ORDER_FIELD_NAME_KEY,
      Type.STRING,
      null,
      Importance.LOW,
      EXPLODE_MODE_DOC,
      "Data",
      3,
      ConfigDef.Width.MEDIUM,
      ORDER_FIELD_NAME_DOC,
    )
    .define(
      CONNECTION_POOL_MAX_IDLE_CONNECTIONS_KEY,
      Type.INT,
      5,
      Importance.LOW,
      CONNECTION_POOL_MAX_IDLE_CONNECTIONS_DOC,
      "Pool",
      1,
      ConfigDef.Width.MEDIUM,
      CONNECTION_POOL_MAX_IDLE_CONNECTIONS_DOC,
    )
    .define(
      CONNECTION_POOL_KEEPALIVE_MILLIS_KEY,
      Type.LONG,
      CONNECTION_POOL_KEEPALIVE_MILLIS_DEFAULT_VALUE,
      Importance.LOW,
      CONNECTION_POOL_KEEPALIVE_MILLIS_DOC,
      "Pool",
      2,
      ConfigDef.Width.LONG,
      CONNECTION_POOL_KEEPALIVE_MILLIS_DOC,
    )
    .define(
      CLOSE_EVERY_CONNECTION_KEY,
      Type.BOOLEAN,
      CLOSE_EVERY_CONNECTION_DEFAULT_VALUE,
      Importance.LOW,
      CLOSE_EVERY_CONNECTION_DOC,
      "Pool",
      3,
      ConfigDef.Width.MEDIUM,
      CLOSE_EVERY_CONNECTION_DOC,
    )
    .define(
      "",
      Type.BOOLEAN,
      CLOSE_EVERY_CONNECTION_DEFAULT_VALUE,
      Importance.LOW,
      CLOSE_EVERY_CONNECTION_DOC,
      "Flattener",
      3,
      ConfigDef.Width.MEDIUM,
      CLOSE_EVERY_CONNECTION_DOC,
    )
    .define(
      DECIMAL_CONVERSION_KEY,
      Type.BOOLEAN,
      DECIMAL_CONVERSION_KEY_DEFAULT,
      Importance.MEDIUM,
      DECIMAL_CONVERSION_KEY_DOC,
    )
    .define(
      NULL_PK_KEY,
      Type.BOOLEAN,
      NULL_PK_KEY_DEFAULT,
      Importance.MEDIUM,
      NULL_PK_KEY_DOC,
    )
    .define(
      FLATTENER_ENABLE_KEY,
      Type.BOOLEAN,
      FLATTENER_ENABLE_DEFAULT,
      Importance.MEDIUM,
      FLATTENER_ENABLE_DOC,
    )
    .define(
      FLATTENER_DISCARD_COLLECTIONS_KEY,
      Type.BOOLEAN,
      FLATTENER_DISCARD_COLLECTIONS_DEFAULT,
      Importance.MEDIUM,
      FLATTENER_DISCARD_COLLECTIONS_DOC,
    )
    .define(
      FLATTENER_JSONBLOB_CHUNKS_KEY,
      Type.INT,
      FLATTENER_JSONBLOB_CHUNKS_DEFAULT,
      Importance.MEDIUM,
      FLATTENER_JSONBLOB_CHUNKS_DOC,
    )
    .define(
      EMBED_KAFKA_EMBEDDED_METADATA_KEY,
      Type.BOOLEAN,
      EMBED_KAFKA_EMBEDDED_METADATA_DEFAULT,
      Importance.MEDIUM,
      EMBED_KAFKA_EMBEDDED_METADATA_DOC,
    )
    .define(
      USE_IN_MEMORY_FS_KEY,
      Type.BOOLEAN,
      USE_IN_MEMORY_FS_DEFAULT,
      Importance.MEDIUM,
      USE_IN_MEMORY_FS_DOC,
    )
    .define(
      SINK_PUT_TIMEOUT_KEY,
      Type.LONG,
      SINK_PUT_TIMEOUT_DEFAULT,
      Importance.HIGH,
      SINK_PUT_TIMEOUT_DOC,
    )
}

class EmsSinkConfigDef() extends ConfigDef with LazyLogging
